const modeSelectionScreen=document.getElementById('mode-selection-screen');const gameWrapper=document.getElementById('game-wrapper');const modeButtons=document.querySelectorAll('.mode-button');const gameTitle=document.getElementById('game-title');const canvas=document.getElementById('game-board');const context=canvas.getContext('2d');const nextCanvas=document.getElementById('next-piece-canvas');const nextContext=nextCanvas.getContext('2d');const holdCanvas=document.getElementById('hold-piece-canvas');const holdContext=holdCanvas.getContext('2d');const scoreBox=document.getElementById('score-box');const scoreLabel=document.getElementById('score-label');const scoreElement=document.getElementById('score');const linesBox=document.getElementById('lines-box');const linesElement=document.getElementById('lines');const timeLevelBox=document.getElementById('time-level-box');const timeLevelLabel=document.getElementById('time-level-label');const timeLevelElement=document.getElementById('time-level');const gameOverScreen=document.getElementById('game-over-screen');const gameOverTitle=document.getElementById('game-over-title');const finalScoreElement=document.getElementById('final-score');const retryButton=document.getElementById('retry-button');const backToMenuButton=document.getElementById('back-to-menu-button');const COLS=10,ROWS=20,BLOCK_SIZE=30,UI_BLOCK_SIZE=25;const PIECES={'I':{shape:[[0,0,0,0],[1,1,1,1],[0,0,0,0],[0,0,0,0]],color:'#00f0f0'},'O':{shape:[[1,1],[1,1]],color:'#f0f000'},'T':{shape:[[0,1,0],[1,1,1],[0,0,0]],color:'#a000f0'},'L':{shape:[[0,0,1],[1,1,1],[0,0,0]],color:'#f0a000'},'J':{shape:[[1,0,0],[1,1,1],[0,0,0]],color:'#0000f0'},'S':{shape:[[0,1,1],[1,1,0],[0,0,0]],color:'#00f000'},'Z':{shape:[[1,1,0],[0,1,1],[0,0,0]],color:'#f00000'}};const PIECE_NAMES=Object.keys(PIECES);const KICKS_JLSTZ=[[[0,0],[-1,0],[-1,1],[0,-2],[-1,-2]],[[0,0],[1,0],[1,-1],[0,2],[1,2]],[[0,0],[1,0],[1,-1],[0,2],[1,2]],[[0,0],[-1,0],[-1,1],[0,-2],[-1,-2]],[[0,0],[1,0],[1,1],[0,-2],[1,-2]],[[0,0],[-1,0],[-1,-1],[0,2],[-1,2]],[[0,0],[-1,0],[-1,-1],[0,2],[-1,2]],[[0,0],[1,0],[1,1],[0,-2],[1,-2]]];const KICKS_I=[[[0,0],[-2,0],[1,0],[-2,-1],[1,2]],[[0,0],[2,0],[-1,0],[2,1],[-1,-2]],[[0,0],[-1,0],[2,0],[-1,2],[2,-1]],[[0,0],[1,0],[-2,0],[1,-2],[-2,1]],[[0,0],[2,0],[-1,0],[2,1],[-1,-2]],[[0,0],[-2,0],[1,0],[-2,-1],[1,2]],[[0,0],[1,0],[-2,0],[1,-2],[2,1]],[[0,0],[-1,0],[2,0],[-1,2],[2,-1]]];const KICK_MAP={'I':KICKS_I,'O':[],'T':KICKS_JLSTZ,'L':KICKS_JLSTZ,'J':KICKS_JLSTZ,'S':KICKS_JLSTZ,'Z':KICKS_JLSTZ};let gameMode,board,bag,currentPiece,nextPiece,holdPiece,canHold,score,lines,level,isPlaying,lastMoveWasRotation;let dropInterval,timerInterval,startTime,elapsedTime,animationFrameId,lastTime,dropCounter;let gamepadState={},prevGamepadState={};let touchMoveInterval;function init(){initCanvas();initEventListeners();initTouchControls()}
function stopGame(){isPlaying=!1;if(timerInterval)clearInterval(timerInterval);if(animationFrameId)cancelAnimationFrame(animationFrameId);animationFrameId=null}
function startGame(mode){stopGame();gameMode=mode;modeSelectionScreen.style.display='none';gameWrapper.style.display='flex';setupUIForMode();resetGameModel();lastTime=0;dropCounter=0;if(gameMode==='sprint'||gameMode==='spinmaster'){startTime=Date.now();elapsedTime=0;timerInterval=setInterval(updateTimer,100)}
isPlaying=!0;gameLoop()}
function initCanvas(){canvas.width=COLS*BLOCK_SIZE;canvas.height=ROWS*BLOCK_SIZE;context.scale(BLOCK_SIZE,BLOCK_SIZE);[nextCanvas,holdCanvas].forEach(c=>{c.width=4*UI_BLOCK_SIZE;c.height=4*UI_BLOCK_SIZE});nextContext.scale(UI_BLOCK_SIZE,UI_BLOCK_SIZE);holdContext.scale(UI_BLOCK_SIZE,UI_BLOCK_SIZE)}
function initEventListeners(){modeButtons.forEach(button=>button.addEventListener('click',()=>startGame(button.dataset.mode)));retryButton.addEventListener('click',()=>{gameOverScreen.style.display='none';startGame(gameMode)});backToMenuButton.addEventListener('click',()=>{stopGame();gameOverScreen.style.display='none';gameWrapper.style.display='none';modeSelectionScreen.style.display='block'})}
function setupUIForMode(){const modeTitles={normal:'通常モード',sprint:'40ライン',spinmaster:'スピンマスター'};gameTitle.textContent=modeTitles[gameMode];scoreBox.style.display=(gameMode!=='sprint')?'block':'none';linesBox.style.display=(gameMode!=='spinmaster')?'block':'none';timeLevelLabel.textContent=(gameMode==='normal')?'LEVEL':'TIME'}
function resetGameModel(){board=Array.from({length:ROWS},()=>Array(COLS).fill(null));bag=[];score=0;lines=0;level=1;canHold=!0;holdPiece=null;dropInterval=1000;lastMoveWasRotation=!1;fillBag();fillBag();currentPiece=getNewPiece();nextPiece=getNewPiece();updateUI();drawAll()}
function gameLoop(time=0){if(!isPlaying)return;handleGamepadInput();if(lastTime>0){const deltaTime=time-lastTime;dropCounter+=deltaTime;if(dropCounter>dropInterval){pieceDrop();dropCounter=0}}
lastTime=time;animationFrameId=requestAnimationFrame(gameLoop)}
function drawBlock(ctx,x,y,color){ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=15;ctx.fillRect(x,y,1,1);ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,0.5)';ctx.lineWidth=0.05;ctx.strokeRect(x,y,1,1)}
function drawGhost(){if(!currentPiece)return;let ghostY=currentPiece.y;while(isValidMove(currentPiece.shape,currentPiece.x,ghostY+1)){ghostY++}
context.globalAlpha=0.3;currentPiece.shape.forEach((row,r)=>{row.forEach((value,c)=>{if(value)drawBlock(context,currentPiece.x+c,ghostY+r,currentPiece.color);})});context.globalAlpha=1.0}
function drawPiece(piece,ctx){if(!piece)return;piece.shape.forEach((row,r)=>row.forEach((value,c)=>{if(value)drawBlock(ctx,piece.x+c,piece.y+r,piece.color);}))}
function drawLockedPieces(){board.forEach((row,y)=>row.forEach((color,x)=>{if(color)drawBlock(context,x,y,color);}))}
function drawAll(){context.clearRect(0,0,canvas.width,canvas.height);drawLockedPieces();drawGhost();drawPiece(currentPiece,context);context.shadowBlur=0;drawNext();drawHold()}
function drawNext(){nextContext.clearRect(0,0,nextCanvas.width,nextCanvas.height);if(!nextPiece||!nextPiece.name)return;const p=PIECES[nextPiece.name],d={shape:p.shape,color:p.color,x:(4-p.shape[0].length)/2,y:(4-p.shape.length)/2};d.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v)drawBlock(nextContext,d.x+x,d.y+y,d.color)}));}
function drawHold(){holdContext.clearRect(0,0,holdCanvas.width,holdCanvas.height);if(!holdPiece)return;const p=PIECES[holdPiece],d={shape:p.shape,color:p.color,x:(4-p.shape[0].length)/2,y:(4-p.shape.length)/2};d.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v)drawBlock(holdContext,d.x+x,d.y+y,d.color)}));}
function getNewPiece(){if(bag.length<PIECE_NAMES.length)fillBag();const n=bag.shift();const p=PIECES[n];return{name:n,shape:p.shape,color:p.color,x:Math.floor(COLS/2)-Math.floor(p.shape[0].length/2),y:n==='I'?-1:0,rotation:0}}
function fillBag(){const t=[...PIECE_NAMES];for(let i=t.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[t[i],t[j]]=[t[j],t[i]]}
bag.push(...t)}
function pieceDrop(){if(!currentPiece)return;if(!isValidMove(currentPiece.shape,currentPiece.x,currentPiece.y+1)){lockPiece()}else{currentPiece.y++;lastMoveWasRotation=!1}
drawAll()}
function hardDrop(){if(!currentPiece)return;while(isValidMove(currentPiece.shape,currentPiece.x,currentPiece.y+1)){currentPiece.y++}
lastMoveWasRotation=!1;lockPiece()}
function rotatePiece(dir){if(!currentPiece||currentPiece.name==='O')return;const size=currentPiece.shape.length;let newShape=Array.from({length:size},()=>Array(size).fill(0));if(dir>0){for(let r=0;r<size;r++)
for(let c=0;c<size;c++)newShape[c][size-1-r]=currentPiece.shape[r][c]}else{for(let r=0;r<size;r++)
for(let c=0;c<size;c++)newShape[size-1-c][r]=currentPiece.shape[r][c]}
const oldRot=currentPiece.rotation;const newRot=(oldRot+(dir>0?1:3))%4;const kickIndex=dir>0?(oldRot*2):(oldRot*2+1);const kickData=KICK_MAP[currentPiece.name];const kicks=kickData&&kickData[kickIndex]?kickData[kickIndex]:[[0,0]];for(const[dx,dy]of kicks){if(isValidMove(newShape,currentPiece.x+dx,currentPiece.y-dy)){currentPiece.x+=dx;currentPiece.y-=dy;currentPiece.shape=newShape;currentPiece.rotation=newRot;lastMoveWasRotation=!0;drawAll();return}}}
function hold(){if(!canHold||!currentPiece)return;canHold=!1;if(holdPiece){const temp=holdPiece;holdPiece=currentPiece.name;currentPiece.name=temp;const p=PIECES[currentPiece.name];currentPiece.shape=p.shape;currentPiece.color=p.color}else{holdPiece=currentPiece.name;currentPiece=nextPiece;nextPiece=getNewPiece()}
if(!currentPiece){gameOver();return}
currentPiece.x=Math.floor(COLS/2)-Math.floor(currentPiece.shape[0].length/2);currentPiece.y=currentPiece.name==='I'?-1:0;currentPiece.rotation=0;if(!isValidMove(currentPiece.shape,currentPiece.x,currentPiece.y)){gameOver()}
drawAll()}
function isValidMove(sh,x,y){for(let r=0;r<sh.length;r++){for(let c=0;c<sh[r].length;c++){if(sh[r][c]>0){const nx=x+c,ny=y+r;if(nx<0||nx>=COLS||ny>=ROWS||(ny>=0&&board[ny][nx]))return!1}}}
return!0}
function lockPiece(){const isTSpin=checkTSpin();currentPiece.shape.forEach((r,y)=>r.forEach((v,x)=>{if(v>0&&currentPiece.y+y>=0)board[currentPiece.y+y][currentPiece.x+x]=currentPiece.color}));canHold=!0;clearLines(isTSpin);if(!isPlaying)return;currentPiece=nextPiece;nextPiece=getNewPiece();if(!currentPiece||!isValidMove(currentPiece.shape,currentPiece.x,currentPiece.y)){gameOver();return}
drawAll()}
function checkTSpin(){if(!currentPiece||currentPiece.name!=='T'||!lastMoveWasRotation)return!1;const{x,y}=currentPiece;const corners=[[y,x],[y,x+2],[y+2,x],[y+2,x+2]];let o=0;for(const[r,c]of corners){if(c<0||c>=COLS||r<0||r>=ROWS||(r>=0&&board[r][c]))o++}
return o>=3}
function clearLines(isTSpin){let cl=0;for(let r=ROWS-1;r>=0;r--){if(board[r].every(c=>c)){board.splice(r,1);board.unshift(Array(COLS).fill(null));cl++;r++}}
if(cl>0){lines+=cl;let s=0;if(gameMode!=='sprint'){if(isTSpin){s=[400,800,1200,1600][cl-1]||400;if(gameMode==='spinmaster')s*=5}else{s=gameMode==='spinmaster'?0:[100,300,500,800][cl-1]}
score+=s*level}
if(gameMode==='normal'&&lines>=level*10){level++;dropInterval=Math.max(100,dropInterval*0.9)}
if(gameMode==='sprint'&&lines>=40){gameOver(!0)}}else if(isTSpin){score+=(gameMode==='spinmaster'?500:100)*level}
updateUI()}
function updateUI(){scoreElement.textContent=score;linesElement.textContent=(gameMode==='sprint')?`${lines} / 40`:lines;if(gameMode==='normal')timeLevelElement.textContent=level}
function updateTimer(){elapsedTime=Date.now()-startTime;const tl=120000;if(gameMode==='sprint'){timeLevelElement.textContent=formatTime(elapsedTime)}else if(gameMode==='spinmaster'){const r=tl-elapsedTime;if(r<=0){timeLevelElement.textContent='0.00';gameOver(!0)}else{timeLevelElement.textContent=formatTime(r)}}}
function formatTime(ms){return(ms/1000).toFixed(2)}
function gameOver(isWin=!1){if(!isPlaying)return;stopGame();const results={sprint:isWin?['CLEAR!',`Time: ${formatTime(elapsedTime)}`]:['GAME OVER',`Lines: ${lines}/40`],spinmaster:['TIME UP!',`Score: ${score}`],normal:['GAME OVER',`Score: ${score}`]};const[title,msg]=results[gameMode];gameOverTitle.textContent=title;finalScoreElement.textContent=msg;gameOverScreen.style.display='block'}
function handleMove(d){if(!isPlaying||!currentPiece)return;if(isValidMove(currentPiece.shape,currentPiece.x+d,currentPiece.y)){currentPiece.x+=d;lastMoveWasRotation=!1;drawAll()}}
function handleSoftDrop(){if(isPlaying){pieceDrop();dropCounter=0}}
function handleHardDrop(){if(isPlaying)hardDrop();}
function handleHold(){if(isPlaying)hold();}
function initTouchControls(){const cs={'touch-left':()=>handleMove(-1),'touch-right':()=>handleMove(1),'touch-down':handleSoftDrop,'touch-rotate-right':()=>rotatePiece(1),'touch-rotate-left':()=>rotatePiece(-1),'touch-drop':handleHardDrop,'touch-hold':handleHold};for(const[id,ac]of Object.entries(cs)){const b=document.getElementById(id);if(!b)continue;const sM=(e)=>{e.preventDefault();if(touchMoveInterval){clearInterval(touchMoveInterval);touchMoveInterval=null}};b.addEventListener('touchstart',(e)=>{e.preventDefault();ac();if(id==='touch-left'||id==='touch-right')touchMoveInterval=setInterval(ac,100);},{passive:!1});b.addEventListener('touchend',sM);b.addEventListener('touchcancel',sM)}}
function handleGamepadInput(){const gps=navigator.getGamepads();if(!gps||!gps[0])return;const gp=gps[0];gamepadState={axes:[gp.axes[0],gp.axes[1]],buttons:gp.buttons.map(b=>b.pressed)};const jP=(i)=>gamepadState.buttons[i]&&!prevGamepadState.buttons?.[i];if(jP(0))rotatePiece(1);if(jP(1)||jP(2))rotatePiece(-1);if(jP(4)||jP(5)||jP(6)||jP(7)||jP(8))handleHold();if(jP(3))handleHardDrop();if(jP(13)||gamepadState.axes[1]>0.5)handleSoftDrop();if(jP(14)||gamepadState.axes[0]<-0.5)handleMove(-1);if(jP(15)||gamepadState.axes[0]>0.5)handleMove(1);prevGamepadState=gamepadState}
document.addEventListener('keydown',e=>{if(!isPlaying)return;switch(e.key){case 'ArrowLeft':handleMove(-1);break;case 'ArrowRight':handleMove(1);break;case 'ArrowDown':handleSoftDrop();break;case 'ArrowUp':rotatePiece(1);break;case 'z':case 'Z':rotatePiece(-1);break;case ' ':e.preventDefault();handleHardDrop();break;case 'c':case 'C':case 'Shift':handleHold();break}});init()